### ISSUE TITLE
Week 1 — Become familiar with Ionic Framework

### ISSUE THREAD

**Issue by mnmckenn** [mnmckenn/Nudge#9]

**Comment by mnmckenn** [comment]
https://thinkster.io/ionic-framework-tutorial

**Comment by montgn2** [comment]
https://www.youtube.com/watch?v=O2WiI9QrS5s&feature=youtu.be

**Comment by montgn2** [comment]
https://www.pluralsight.com/guides/front-end-javascript/ionic-framework-a-definitive-10-000-word-guide
